name: code-formatting

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  main:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    timeout-minutes: 5
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: EditorConfig-Action
        uses: zbeekman/EditorConfig-Action@v1.1.1
      - name: Lint with Ruff
        run: poetry run ruff --output-format=github
